// AutoScript/src/app/buy-as-guest/buy-as-guest.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-buy-as-guest',
  templateUrl: './buy-as-guest.component.html',
  styleUrl: './buy-as-guest.component.scss'
})
export class BuyAsGuestComponent {

}

<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <!--<meta name=description content="This site was generated with Anima. www.animaapp.com"/>-->
    <!-- <link rel="shortcut icon" type=image/png href="https://animaproject.s3.amazonaws.com/home/favicon.png" /> -->
    <meta name="viewport" content="width=1920, maximum-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="https://animaproject.s3.amazonaws.com/home/favicon.png"
    />
    <meta name="og:type" content="website" />
    <meta name="twitter:card" content="photo" />
    <link rel="stylesheet" type="text/css" href="buy-as-guest.component.scss" />
    <link rel="stylesheet" type="text/css" href="./styleguide.css" />
    <link rel="stylesheet" type="text/css" href="./globals.css" />
  </head>
  <body style="margin: 0; background: #000000">
    <input type="hidden" id="anPageName" name="page" value="buy-as-guest" />
    <div class="container-center-horizontal">
      <div class="buy-as-guest screen">
        <div class="navbar">
          <div class="overlap-group7">
            <img
              class="icon-black"
              src="img/icon-black-10@1x.png"
              alt="Icon Black"
            />
            <div class="blackbackground"></div>
            <a href="products.html"
              ><div class="products malgungothic-regular-normal-coconut-37px">
                Products
              </div> </a
            ><a href="login.html"
              ><img
                class="user-128"
                src="img/user-128-10@1x.png"
                alt="user-128"
              /> </a
            ><img
              class="x629578-200"
              src="img/629578-200-10@1x.png"
              alt="629578-200"
            />
            <a href="cart.html"
              ><img
                class="x231-2317666_cart-ico"
                src="img/231-2317666-cart-icon-moving-shopping-cart-icon-10@1x.png"
                alt="231-2317666_cart-icon-moving-shopping-cart-icon"
              /> </a
            ><a href="home.html">
              <div class="gruppe-22 gruppe">
                <div class="icon-white"></div></div></a
            ><img
              class="linie-3 linie"
              src="img/linie-3-10@1x.png"
              alt="Linie 3"
            />
            <a href="taskboard.html"
              ><div class="requests malgungothic-regular-normal-coconut-37px">
                Requests
              </div>
            </a>
          </div>
        </div>
        <h1 class="title malgungothic-regular-normal-gallery-70px">
          Buy as Guest
        </h1>
        <div class="step-1">
          <div
            class="step-1-registration malgungothic-regular-normal-gallery-50px"
          >
            Step 1 Registration
          </div>
          <div class="tobefield-fields">
            <div class="overlap-group-container">
              <div class="overlap-group">
                <div class="komponente-44-1">
                  <div class="firstname malgungothic-regular-normal-black-30px">
                    Firstname
                  </div>
                </div>
              </div>
              <div class="overlap-group">
                <div class="komponente-46-1">
                  <div class="place malgungothic-regular-normal-black-30px">
                    Street
                  </div>
                </div>
              </div>
              <div class="overlap-group">
                <div class="komponente-48-1">
                  <div class="country malgungothic-regular-normal-black-30px">
                    country
                  </div>
                </div>
              </div>
              <div class="overlap-group-1">
                <div class="komponente-49-1">
                  <div class="email malgungothic-regular-normal-black-30px">
                    Email
                  </div>
                </div>
              </div>
            </div>
            <div class="overlap-group-container-1">
              <div class="overlap-group-1">
                <div class="komponente-45-1">
                  <div class="lastname malgungothic-regular-normal-black-30px">
                    Lastname
                  </div>
                </div>
              </div>
              <div class="overlap-group-1">
                <div class="komponente-47-1">
                  <div class="place-1 malgungothic-regular-normal-black-30px">
                    Place
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="overlap-group8">
          <div class="step2">
            <div
              class="step-2-select-paymant step-2-select malgungothic-regular-normal-black-50px"
            >
              Step 2 Select Paymant
            </div>
            <div class="flex-row flex malgungothic-regular-normal-black-50px">
              <div class="paypal">Paypal</div>
              <div class="ellipse-5 ellipse"></div>
              <div class="mastercard">Mastercard</div>
              <div class="ellipse-6 ellipse"></div>
            </div>
            <div class="flex-row-1">
              <div class="invoice malgungothic-regular-normal-black-50px">
                invoice
              </div>
              <div class="ellipse"></div>
            </div>
          </div>
          <div class="step2-1">
            <div class="flex-col flex">
              <div
                class="step-2-select-payment step-2-select malgungothic-regular-normal-gallery-50px"
              >
                Step 2 Select Payment
              </div>
              <div class="invoice-1 malgungothic-regular-normal-gallery-50px">
                Invoice
              </div>
              <div class="flex-row-2">
                <div class="paypal-1 malgungothic-regular-normal-gallery-50px">
                  Paypal
                </div>
                <div class="komponente-30-4"></div>
              </div>
            </div>
            <div class="mastercard-1 malgungothic-regular-normal-gallery-50px">
              Mastercard
            </div>
            <div class="komponente-30-3 komponente-30-4"></div>
          </div>
          <div class="komponente-30-1 komponente-30-4"></div>
        </div>
        <div class="step-3 malgungothic-regular-normal-gallery-40px">
          <div class="flex-col-1">
            <div
              class="step-3-confirm-cart malgungothic-regular-normal-gallery-50px"
            >
              Step 3 Confirm Cart
            </div>
            <div
              class="pyton-autoupdater malgungothic-regular-normal-gallery-40px"
            >
              Pyton autoupdater
            </div>
            <div
              class="efficiency-script malgungothic-regular-normal-gallery-40px"
            >
              Efficiency script
            </div>
            <div class="total malgungothic-regular-normal-gallery-40px">
              Total:
            </div>
            <div class="flex-row-3">
              <div
                class="confirm-cart malgungothic-regular-normal-gallery-50px"
              >
                Confirm Cart
              </div>
              <div class="komponente-30"></div>
            </div>
            <div class="flex-row-4">
              <div class="accept-agb malgungothic-regular-normal-gallery-50px">
                Accept AGB
              </div>
              <div class="komponente-30"></div>
            </div>
          </div>
          <div class="number-container">
            <div class="number">2</div>
            <div class="number-1">4</div>
          </div>
          <div class="text-container">
            <div class="text-9">200.-</div>
            <div class="text-8">116.-</div>
            <div class="text-10">316.-</div>
          </div>
        </div>
        <div class="buttons">
          <div class="overlap-group-2">
            <a href="buy-as-guest-message.html">
              <div class="rechteck-24"></div
            ></a>
            <div class="buy">
              <span class="malgungothic-regular-normal-gallery-50px"
                >&nbsp;</span
              ><span class="malgungothic-regular-normal-black-50px">Buy</span>
            </div>
          </div>
          <div class="overlap-group1">
            <a href="cart.html"
              ><img class="pfad-39" src="img/pfad-39@1x.png" alt="Pfad 39" />
            </a>
            <div class="cancel malgungothic-regular-normal-white-50px">
              Cancel
            </div>
          </div>
        </div>
        <footer class="footer">
          <div class="overlap-group6">
            <img
              class="background"
              src="img/background-19@1x.png"
              alt="background"
            />
            <a href="home.html"
              ><img
                class="auto-script-shop-hig"
                src="img/auto-script-shop-high-resolution-logo-white-on-transparent-backg-10@1x.png"
                alt="auto-script-shop-high-resolution-logo-white-on-transparent-background"
              />
            </a>
            <div class="gruppe-38 gruppe">
              <a href="about-us.html"
                ><div class="about malgungothic-regular-normal-white-35px">
                  About
                </div> </a
              ><a href="impressum.html"
                ><div class="impressum malgungothic-regular-normal-white-35px">
                  Impressum
                </div> </a
              ><a href="disclamer.html"
                ><div class="disclaimer malgungothic-regular-normal-white-35px">
                  Disclaimer
                </div> </a
              ><a href="terms-conditions.html"
                ><div
                  class="terms-conditions malgungothic-regular-normal-white-35px"
                >
                  Terms &amp; Conditions
                </div>
              </a>
            </div>
            <img
              class="linie-2 linie"
              src="img/linie-2-10@1x.png"
              alt="Linie 2"
            />
            <div class="gruppe-49 gruppe">
              <a href="blog.html"
                ><div class="blog malgungothic-regular-normal-white-35px">
                  Blog
                </div>
              </a>
            </div>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

// auto-script-shop/src/screens/BuyAsGuest/BuyAsGuest.jsx
import React from "react";
import { Link } from "react-router-dom";
import "./style.css";

export const BuyAsGuest = () => {
  return (
    <div className="buy-as-guest">
      <div className="div-20">
        <div className="title-11">Buy as Guest</div>
        <div className="buttons">
          <div className="overlap-group-20">
            <Link className="rechteck-6" to="/buy-confirmation" />
            <p className="buy">
              <span className="text-wrapper-182">&nbsp;</span>
              <span className="text-wrapper-183">Buy</span>
            </p>
          </div>
          <div className="overlap-54">
            <Link to="/shoppingcart">
              <img className="pfad-15" alt="Pfad" src="/img/pfad-39.png" />
            </Link>
            <div className="text-wrapper-184">Cancel</div>
          </div>
        </div>
        <div className="step">
          <div className="tobefield-fields">
            <div className="komponente-wrapper">
              <div className="komponente-17">
                <div className="text-wrapper-185">Firstname</div>
              </div>
            </div>
            <div className="overlap-55">
              <div className="komponente-18">
                <div className="text-wrapper-185">Lastname</div>
              </div>
            </div>
            <div className="overlap-56">
              <div className="komponente-19">
                <div className="text-wrapper-185">Street</div>
              </div>
            </div>
            <div className="overlap-57">
              <div className="komponente-20">
                <div className="text-wrapper-185">Place</div>
              </div>
            </div>
            <div className="overlap-group-21">
              <div className="komponente-21">
                <div className="text-wrapper-185">country</div>
              </div>
            </div>
            <div className="overlap-58">
              <div className="komponente-22">
                <div className="text-wrapper-185">Email</div>
              </div>
            </div>
          </div>
          <div className="text-wrapper-186">Step 1 Registration</div>
        </div>
        <div className="overlap-59">
          <div className="step-2">
            <div className="text-wrapper-187">Step 2 Select Paymant</div>
            <div className="text-wrapper-188">Paypal</div>
            <div className="text-wrapper-189">Mastercard</div>
            <div className="ellipse-13" />
            <div className="ellipse-14" />
            <div className="text-wrapper-190">invoice</div>
            <div className="ellipse-15" />
          </div>
          <div className="step-3">
            <div className="text-wrapper-191">Step 2 Select Payment</div>
            <div className="text-wrapper-192">Invoice</div>
            <div className="text-wrapper-193">Mastercard</div>
            <div className="text-wrapper-194">Paypal</div>
            <div className="komponente-23" />
            <div className="komponente-24" />
          </div>
          <div className="komponente-25" />
        </div>
        <div className="step-4">
          <div className="text-wrapper-195">Step 3 Confirm Cart</div>
          <div className="text-wrapper-196">Efficiency script</div>
          <div className="text-wrapper-197">4</div>
          <div className="text-wrapper-198">116.-</div>
          <div className="text-wrapper-199">Pyton autoupdater</div>
          <div className="text-wrapper-200">2</div>
          <div className="text-wrapper-201">200.-</div>
          <div className="text-wrapper-202">Total:</div>
          <div className="text-wrapper-203">316.-</div>
          <div className="text-wrapper-204">Confirm Cart</div>
          <div className="text-wrapper-205">Accept AGB</div>
          <div className="komponente-26" />
          <div className="komponente-27" />
        </div>
        <footer className="footer-13">
          <div className="overlap-60">
            <img className="background-16" alt="Background" src="/img/background-40.png" />
            <Link to="/home">
              <img
                className="auto-script-shop-14"
                alt="Auto script shop"
                src="/img/auto-script-shop-high-resolution-logo-white-on-transparent-backg-22.png"
              />
            </Link>
            <div className="gruppe-84">
              <Link className="text-wrapper-206" to="/about-us">
                About{" "}
              </Link>
              <Link className="text-wrapper-207" to="/disclamer">
                Disclaimer
              </Link>
              <Link className="text-wrapper-208" to="/impressum">
                Impressum
              </Link>
              <Link className="terms-conditions-12" to="/terms-conditions">
                Terms &amp; Conditions
                <br />
              </Link>
            </div>
            <img className="linie-29" alt="Linie" src="/img/linie-2-22.png" />
            <div className="gruppe-85">
              <Link className="text-wrapper-206" to="/blog">
                Blog{" "}
              </Link>
            </div>
          </div>
        </footer>
        <div className="navbar-8">
          <div className="overlap-61">
            <img className="icon-black-13" alt="Icon black" src="/img/icon-black-29.png" />
            <div className="blackbackground-13" />
            <Link className="text-wrapper-209" to="/shop">
              Products
            </Link>
            <img className="user-13" alt="User" src="/img/user-128-24.png" />
            <img className="element-13" alt="Element" src="/img/629578-200-24.png" />
            <Link to="/shoppingcart">
              <img
                className="element-cart-13"
                alt="Element cart"
                src="/img/231-2317666-cart-icon-moving-shopping-cart-icon-24.png"
              />
            </Link>
            <Link className="gruppe-86" to="/home">
              <div className="icon-white-13" />
            </Link>
            <img className="linie-30" alt="Linie" src="/img/linie-3-24.png" />
            <Link className="requests-13" to="/taskboard">
              Requests
              <br />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
